### PR TITLE
Make FPN, top-down and backbone configurable 

### LINKED ISSUE #170: An error raise when positive_overlaps has shape (0,0), how to fix?
Sometimes, a picture gives no positive_roi, and this will raise an error:

W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Reduction axis 1 is empty in shape [0,0]
	 [[Node: proposal_targets/ArgMax = ArgMax[T=DT_FLOAT, Tidx=DT_INT32, output_type=DT_INT64, _device="/job:localhost/replica:0/task:0/device:GPU:0"](proposal_targets/Gather_5, rpn_class_loss/Equal/y)]]
Traceback (most recent call last):
  File "/home/xxx/anaconda2/envs/py36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1323, in _do_call
    return fn(*args)
  File "/home/xxx/anaconda2/envs/py36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1302, in _run_fn
    status, run_metadata)
  File "/home/xxx/anaconda2/envs/py36/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Reduction axis 1 is empty in shape [0,0]
	 [[Node: proposal_targets/ArgMax = ArgMax[T=DT_FLOAT, Tidx=DT_INT32, output_type=DT_INT64, _device="/job:localhost/replica:0/task:0/device:GPU:0"](proposal_targets/Gather_5, rpn_class_loss/Equal/y)]]
	 [[Node: roi_align_classifier/Cast_2/_7079 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_8551_roi_align_classifier/Cast_2", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "portrait_seg.py", line 206, in <module>
    layers='4+')
  File "/home/xxx/Desktop/keras_Mask_RCNN/model.py", line 2211, in train
    use_multiprocessing=True,
  File "/home/xxx/anaconda2/envs/py36/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "/home/xxx/anaconda2/envs/py36/lib/python3.6/site-packages/keras/engine/training.py", line 2096, in fit_generator
    class_weight=class_weight)
  File "/home/xxx/anaconda2/envs/py36/lib/python3.6/site-packages/keras/engine/training.py", line 1814, in train_on_batch
    outputs = self.train_function(ins)
  File "/home/xxx/anaconda2/envs/py36/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 2352, in __call__
    **self.session_kwargs)
  File "/home/xxx/anaconda2/envs/py36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 889, in run
    run_metadata_ptr)
  File "/home/xxx/anaconda2/envs/py36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1120, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/xxx/anaconda2/envs/py36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1317, in _do_run
    options, run_metadata)
  File "/home/xxx/anaconda2/envs/py36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1336, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Reduction axis 1 is empty in shape [0,0]
	 [[Node: proposal_targets/ArgMax = ArgMax[T=DT_FLOAT, Tidx=DT_INT32, output_type=DT_INT64, _device="/job:localhost/replica:0/task:0/device:GPU:0"](proposal_targets/Gather_5, rpn_class_loss/Equal/y)]]
	 [[Node: roi_align_classifier/Cast_2/_7079 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_8551_roi_align_classifier/Cast_2", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

Caused by op 'proposal_targets/ArgMax', defined at:
  File "portrait_seg.py", line 168, in <module>
    model_dir=MODEL_DIR)
  File "/home/xxx/Desktop/keras_Mask_RCNN/model.py", line 1744, in __init__
    self.keras_model = self.build(mode=mode, config=config)
  File "/home/xxx/Desktop/keras_Mask_RCNN/model.py", line 1885, in build
    target_rois, input_gt_class_ids, gt_boxes, input_gt_masks])
  File "/home/xxx/anaconda2/envs/py36/lib/python3.6/site-packages/keras/engine/topology.py", line 603, in __call__
    output = self.call(inputs, **kwargs)
  File "/home/xxx/Desktop/keras_Mask_RCNN/model.py", line 641, in call
    self.config.IMAGES_PER_GPU, names=names)
  File "/home/xxx/Desktop/keras_Mask_RCNN/utils.py", line 673, in batch_slice
    output_slice = graph_fn(*inputs_slice)
  File "/home/xxx/Desktop/keras_Mask_RCNN/model.py", line 640, in <lambda>
    w, x, y, z, self.config),
  File "/home/xxx/Desktop/keras_Mask_RCNN/model.py", line 544, in detection_targets_graph
    roi_gt_box_assignment = tf.argmax(positive_overlaps, axis=1)
  File "/home/xxx/anaconda2/envs/py36/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 316, in new_func
    return func(*args, **kwargs)
  File "/home/xxx/anaconda2/envs/py36/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py", line 205, in argmax
    return gen_math_ops.arg_max(input, axis, name=name, output_type=output_type)
  File "/home/xxx/anaconda2/envs/py36/lib/python3.6/site-packages/tensorflow/python/ops/gen_math_ops.py", line 441, in arg_max
    name=name)
  File "/home/xxx/anaconda2/envs/py36/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/xxx/anaconda2/envs/py36/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2956, in create_op
    op_def=op_def)
  File "/home/xxx/anaconda2/envs/py36/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1470, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): Reduction axis 1 is empty in shape [0,0]
	 [[Node: proposal_targets/ArgMax = ArgMax[T=DT_FLOAT, Tidx=DT_INT32, output_type=DT_INT64, _device="/job:localhost/replica:0/task:0/device:GPU:0"](proposal_targets/Gather_5, rpn_class_loss/Equal/y)]]
	 [[Node: roi_align_classifier/Cast_2/_7079 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_8551_roi_align_classifier/Cast_2", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

I tried to fix this by add a check if there is a positive_indices, in model.py, line528:

    # Subsample ROIs. Aim for 33% positive
    # Positive ROIs
    positive_count = int(config.TRAIN_ROIS_PER_IMAGE *
                         config.ROI_POSITIVE_RATIO)
    positive_indices = tf.random_shuffle(positive_indices)[:positive_count]
    a = positive_indices.get_shape()[0]
    if a == 0:
        positive_indices = tf.constant([1])
    positive_count = tf.shape(positive_indices)[0]

However, it can avoid some wrong cases, but still raise error in other cases.
How to fix this throghly?

### PR DESCRIPTION
**Pull request by julienr**
This adds two new config options : `Config.FPN_CLASSIF_FC_LAYERS_SIZE` and `Config.TOP_DOWN_PYRAMID_SIZE` to allow the user to specify the size of those layers.

This also adds a `Config.BACKBONE` option that allow one to use a custom backbone by providing a function that should return a backbone graph.

Also fix #170 and allow dashes in model name when trying to restart from an epoch.

### CODE REVIEW

**Comment by benqua** [comment]
+1 would love to see this PR merged. It fixes two issues I am facing right now!

(BTW, wouldn't it be better (easier to get merged) to have 4 distinct PR?)

**Comment by julienr** [comment]
I can definitely split this into 4 if it's easier; whatever the maintainer prefers

**Comment by waleedka** [comment]
Interesting additions. The three commits that add the backbone configuration and allow dashes in model names look good and elegantly done. 

The fix for #170 is, I think, a step in the right direction but doesn't completely solve the problem. It solves the case when there are no ground truth boxes, but the code still fails at a later stage. In my test, on TF 1.8, I get a core dump. But, one step at a time, so I'll merge this and address the other issue separately.

Thank you, great PR.

**Comment by julienr** [comment]
Thanks for merging !

**Pull request merged**
