### PR TITLE
Support for changing optimizer, data augmentation

### PR DESCRIPTION
**Pull request by spotiris**
Added support for changing optimizer and optimizer parameters with minimal changes to overall interface.
The main interface change is that the LR is now specified in the training config, and instead a learning_rate_multiplier is given as an argument to model.train().
The train_shapes example has been updated to test this.

### CODE REVIEW

**Comment by John1231983** [comment]
@spotiris : Great job. This is my looking for a long time. Have you test with this? Possible to use Adam, instead of NAdam?

**Comment by spotiris** [comment]
Yes I have tested this with NAdam, it should work with Adam and any other optimiser you choose.
Simply change the OPTIMIZER variable in the config to "Adam" and change the OPTIMIZER_PARAMS to a dictionary that represents the [optimizer parameters](https://keras.io/optimizers/#tfoptimizer).

**Comment by spotiris** [comment]
It says in the Optimizer documentation that "The parameters clipnorm and clipvalue can be used with all optimizers to control gradient clipping".
Because the OPTIMIZER_PARAMS variable is a dictionary that is used to specify the keyword arguments to the solver of your choice, you can simply add 'clipnorm' as a key in the dict and specify your value.
Apologies for not remembering to put that in the config.

The second thing you want is a learning rate schedule, which is not implemented here nor in the master branch. What is implemented in the master is the ability to specify the learning rate on a call to train(), however the learning rate should be specified in the OPTIMIZER_PARAMS.
In this pull request the implementation changed being able to specify the learning rate for train() to being able to specify a multiplier for the learning rate.
So you still need to control the learning_rate_multiplier and the number of epochs as in coco.py, and call model.train() multiple times.

**Comment by spotiris** [comment]
I haven't tried the data augmentation with a real dataset yet, only the shapes dataset. I'll let you know in around 24hrs when I try one of my datasets.

**Comment by John1231983** [comment]
OK. And one more thing, something error when I use `augmentations.append(iaa.Affine(**config.AUGMENTATION_AFFINE))`

The error is
```
Traceback (most recent call last):
  File "/home/john/dbs/model.py", line 1659, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "/home/john/dbs/model.py", line 1247, in load_image_gt
    mask = utils.minimize_mask(bbox, mask, config.MINI_MASK_SHAPE)
  File "/home/john/dbs/utils.py", line 464, in minimize_mask
    raise TrainingError("Invalid bounding box with area of zero")
utils.TrainingError: Invalid bounding box with area of zero
ERROR:root:Skipping due to training error on image 
```

This is config
```
    AUGMENTATION_AFFINE = {
        "scale": {"x": (0.8, 1.2), "y": (0.8, 1.2)},
        "translate_percent": {"x": (-0.2, 0.2), "y": (-0.2, 0.2)},
        "rotate": (-5, 5),
        "shear": (-5, 5),
        "order": 0,
        #"clipnorm": 5.0
    }
USE_MINI_MASK = True
```
Note that, `clipnorm` is unused due to some error when use it as ` raise value
TypeError: __init__() got an unexpected keyword argument 'clipnorm'`

**Comment by wolfman30** [comment]
@John1231983 .
how did you solve that last problem to make 'augmentations.append(iaa.Affine(**config.AUGMENTATION_AFFINE))' work?

**Comment by John1231983** [comment]
@wolfman30 : It still  has bug. I did not solve it and igore this PR

**Comment by wolfman30** [comment]
Ok @John1231983  thank you for the prompt reply. 

One more thing: How did you get to 0.473 on the LB?

**Comment by John1231983** [comment]
Hi. I just use mask rcnn from this repo. I use the same learning schedule as coco. I also use coco pretrain with resnet 101, refine dataset from someone. You can try it. Let me know how much LB do you achieve with this strategy. Hope it help you

**Comment by wolfman30** [comment]
Do you mean the LR schedule in coco.py?

**Comment by spotiris** [comment]
I accidently put clipnorm in the data augmentation config when it was supposed to go in to the optimizer config, although I had fixed it shortly after. Pull again from this repo to fix it. 
I have also added a feature to change the LR when a plateau is detected in the validation loss (or other metric of choice).

**Comment by jameschartouni** [comment]
Apologies for my ignorance, but how would I be able to pull the mask r-cnn branch that steve p committed that added data augmentation but did not yet get accepted to the master branch? Thank you in advance.

**Comment by spotiris** [comment]
Redoing pull request because too many features have accumulated into the one request.

**Pull request closed without merging**
