### PR TITLE
Added automated epoch recognition for Windows.

### PR DESCRIPTION
**Pull request by maxfrei750**
Added a regex for Windows paths.

### CODE REVIEW

**Comment by HHoofs** [comment]
Why not ~~~regex = r".*[/\\][\w-]+(\d{4})(\d{2})(\d{2})T(\d{2})(\d{2})[/\\]mask\_rcnn\_[\w-]+(\d{4})\.h5"~~~

**Comment by maxfrei750** [comment]
The most likely reason may very well be that I'm not good at regular expressions. 😅 

Have you tested you solution?

**Comment by HHoofs** [comment]
For me it works, but maybe some tests would be a good idea?

**Comment by maxfrei750** [comment]
@HHoofs I tested your solution and it worked for me as well. Therefore I added a commit to this PR.

**Comment by HHoofs** [comment]
Nice, I think this is a nice easy fix

**Pull request merged**
