### PR TITLE
Fix word & Feat: If multiple anchors have the same IoU.

### PR DESCRIPTION
**Pull request by JNingWei**

### CODE REVIEW

**Comment by JNingWei** [comment]
Fix word

**Comment by JNingWei** [comment]
Feat: If multiple anchors have the same IoU.

**Comment by waleedka** [comment]
I think the update to match multiple anchors is not correct. Have you tested it?

**Comment by JNingWei** [comment]
@waleedka 
Sorry, I just wrote a simple array to test it. Maybe my test method is not entirely correct.

**Comment by JNingWei** [comment]
@waleedka 
I re-tested my code carefully and found that I was wrong. Thank you for your reminder, I will be carefully tested next time.

**Comment by waleedka** [comment]
Thank you! I cherry-picked the one commit that has the spelling error and merged it.

**Pull request closed without merging**
