### PR TITLE
add CI testing

### PR DESCRIPTION
**Pull request by Borda**
add a CI testing, initially in #130

### CODE REVIEW

**Comment by Borda** [comment]
@waleedka ^^

**Comment by Borda** [comment]
@waleedka this seems to be also ready just register for your accounts and change badges and hashes, it is made in the code by TODO

**Comment by Borda** [comment]
@waleedka the badge with failing is because the proper testing is this branch and the tag shows master without proper configuration...

**Comment by Borda** [comment]
@waleedka ^^

**Comment by Borda** [comment]
@waleedka  ^^

**Comment by Borda** [comment]
@waleedka ^^

**Comment by Borda** [comment]
@waleedka ^^ any update?

**Comment by Borda** [comment]
@waleedka ^^ any update?

**Comment by Borda** [comment]
@waleedka any update?

**Comment by Borda** [comment]
@waleedka ^^

**Comment by Borda** [comment]
@waleedka ^^

**Comment by Borda** [comment]
@waleedka  is this repository still active?

**Comment by PavlosMelissinos** [comment]
I suppose not :(

**Pull request closed without merging**
